; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; criar ambiente para debug e teste depois

[platformio] ; configurações gerais em nível de projeto.
default_envs = esp32
description = Projeto base para ESP32 com mDash e WiFiManager
; Suporte a atualizações OTA
; Reset de credenciais Wifi via Interrupts



[env] ; configurações comuns a todos os ambientes
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = time 
build_flags = -DCORE_DEBUG_LEVEL=3  ;(0=NONE, 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG, 5=VERBOSE)
board_build.flash_mode = dio


[env:esp32] ; configurações específicas para o ambiente esp32
platform = espressif32
framework = arduino
board = esp32dev
; Partições de memória
board_build.partitions = min_spiffs.csv  
	; default.csv (padrão)
	; min_spiffs.csv (SPIFFS mínimo, ideal para OTA e mDash)
	; huge_app.csv (aplicativo maior, menos espaço para SPIFFS)
	; minimal.csv (partição mínima)


lib_deps = 
	cesanta/mDash@^1.2.16
	tzapu/WiFiManager@^2.0.17
